#!/bin/sh

if [ $# -gt 0 ] ; then
  FILENAME="$1"
else
  FILENAME='demo0.mm'
fi

sbcl --load "metamath.lisp" \
     --eval "(progn
              (in-package :metamath)
              (metamath:load-mmfile \"$FILENAME\")
              (metamath:process-metamath-file))"

