#!/bin/sh

if [ $# -gt 0 ] ; then
  FILENAME="$1"
else
  FILENAME='demo0.mm'
fi

sbcl <<END
(require :asdf)
(asdf:load-system :cl-metamath)
(in-package :cl-metamath)
(cl-metamath:load-mmfile "$FILENAME")
(cl-metamath:process-metamath-file)
END
